// snake_vm.gen.hpp — auto-generated by py2vmp.py from snake_logic.py
// DO NOT EDIT — regenerate with:  python py2vmp.py snake_logic.py -o snake_vm.gen.hpp
//
// 66 BBs, 249 instructions, 12 pool entries, 12 native sites
#pragma once

#include "test_blob_builder.hpp"
#include <vm/vm_opcode.hpp>
#include <vm/vm_insn.hpp>
#include <cstdint>
#include <vector>

namespace SnakeVM {

using VMPilot::Common::VM::VmOpcode;
using VMPilot::Test::TestBB;
using VMPilot::Test::TestNativeCall;

// ── Register map ──
//   r 8 = hx
//   r 9 = hy
//   r10 = direction
//   r11 = ax
//   r12 = ay
//   r13 = score
//   r14 = body_len
//   r 6 = ZERO (0)
//   r 7 = ONE (1)
//   temps: [15, 5, 4, 3, 2, 1]

enum NativeSlot : uint32_t {
    NATIVE_READ_KEY = 0,
    NATIVE_BODY_INIT = 1,
    NATIVE_BODY_GET_X = 2,
    NATIVE_BODY_GET_Y = 3,
    NATIVE_BODY_SHIFT = 4,
    NATIVE_BODY_SET_HEAD = 5,
    NATIVE_BODY_TRIM = 6,
    NATIVE_RANDOM = 7,
    NATIVE_DRAW = 8,
    NATIVE_SLEEP = 9,
    NATIVE_PLACE_APPLE = 10,
    NATIVE_COUNT = 11,
};

inline const std::vector<uint64_t>& pool() {
    static const std::vector<uint64_t> p = {
        30ULL,  // [0]
        2ULL,  // [1]
        15ULL,  // [2]
        3ULL,  // [3]
        113ULL,  // [4]
        81ULL,  // [5]
        119ULL,  // [6]
        115ULL,  // [7]
        97ULL,  // [8]
        100ULL,  // [9]
        4ULL,  // [10]
        65536ULL,  // [11]
    };
    return p;
}

struct NativeSite {
    uint32_t global_ip;
    uint32_t arg_count;
    uint32_t slot;
};

struct Program {
    std::vector<TestBB> bbs;
    std::vector<NativeSite> native_sites;
};

inline Program build() {
    Program prog;

    // ── BB 1  (28 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 1; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(1 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 15, 0, 0},  // = 30
            {VmOpcode::LOAD_CONST, 128, 5, 0, 1},  // = 2
            {VmOpcode::DIV, 80, 15, 5, 0},
            {VmOpcode::MOVE, 80, 8, 15, 0},
            {VmOpcode::LOAD_CONST, 128, 15, 0, 2},  // = 15
            {VmOpcode::LOAD_CONST, 128, 5, 0, 1},  // = 2
            {VmOpcode::DIV, 80, 15, 5, 0},
            {VmOpcode::MOVE, 80, 9, 15, 0},
            {VmOpcode::MOVE, 80, 10, 7, 0},
            {VmOpcode::MOVE, 80, 13, 6, 0},
            {VmOpcode::LOAD_CONST, 128, 15, 0, 3},  // = 3
            {VmOpcode::MOVE, 80, 14, 15, 0},
            {VmOpcode::MOVE, 80, 0, 8, 0},
            {VmOpcode::MOVE, 80, 1, 9, 0},
            {VmOpcode::MOVE, 80, 2, 14, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 0},  // native_body_init
            {VmOpcode::LOAD_CONST, 128, 15, 0, 0},  // = 30
            {VmOpcode::MOVE, 80, 0, 7, 0},
            {VmOpcode::MOVE, 80, 1, 15, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 1},  // native_random
            {VmOpcode::MOVE, 80, 11, 0, 0},
            {VmOpcode::LOAD_CONST, 128, 15, 0, 2},  // = 15
            {VmOpcode::MOVE, 80, 0, 7, 0},
            {VmOpcode::MOVE, 80, 1, 15, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 2},  // native_random
            {VmOpcode::MOVE, 80, 12, 0, 0},
            {VmOpcode::MOVE, 80, 15, 6, 0},
            {VmOpcode::JMP, 0, 0, 0, 2},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 2  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 2; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(2 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 3},
            {VmOpcode::JMP, 0, 0, 0, 4},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 3  (6 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 3; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(3 * 37 + i);
        bb.instructions = {
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 3},  // native_read_key
            {VmOpcode::MOVE, 80, 5, 0, 0},
            {VmOpcode::LOAD_CONST, 128, 4, 0, 4},  // = 113
            {VmOpcode::CMP, 80, 5, 4, 0},
            {VmOpcode::JCC, 0, 0, 0, 6},
            {VmOpcode::JMP, 0, 0, 0, 7},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 6  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 6; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(6 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 4, 0, 1},  // = 2
            {VmOpcode::MOVE, 80, 15, 4, 0},
            {VmOpcode::JMP, 0, 0, 0, 5},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 7  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 7; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(7 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 4, 0, 5},  // = 81
            {VmOpcode::CMP, 80, 5, 4, 0},
            {VmOpcode::JCC, 0, 0, 0, 6},
            {VmOpcode::JMP, 0, 0, 0, 5},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 5  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 5; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(5 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 9},
            {VmOpcode::JMP, 0, 0, 0, 8},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 9  (5 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 9; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(9 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 4, 10, 0},
            {VmOpcode::LOAD_CONST, 128, 3, 0, 6},  // = 119
            {VmOpcode::CMP, 80, 5, 3, 0},
            {VmOpcode::JCC, 0, 0, 0, 11},
            {VmOpcode::JMP, 0, 0, 0, 12},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 11  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 11; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(11 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 4, 6, 0},
            {VmOpcode::JMP, 0, 0, 0, 10},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 12  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 12; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(12 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 7},  // = 115
            {VmOpcode::CMP, 80, 5, 3, 0},
            {VmOpcode::JCC, 0, 0, 0, 14},
            {VmOpcode::JMP, 0, 0, 0, 15},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 14  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 14; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(14 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 1},  // = 2
            {VmOpcode::MOVE, 80, 4, 3, 0},
            {VmOpcode::JMP, 0, 0, 0, 13},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 15  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 15; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(15 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 8},  // = 97
            {VmOpcode::CMP, 80, 5, 3, 0},
            {VmOpcode::JCC, 0, 0, 0, 17},
            {VmOpcode::JMP, 0, 0, 0, 18},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 17  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 17; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(17 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 3},  // = 3
            {VmOpcode::MOVE, 80, 4, 3, 0},
            {VmOpcode::JMP, 0, 0, 0, 16},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 18  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 18; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(18 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 9},  // = 100
            {VmOpcode::CMP, 80, 5, 3, 0},
            {VmOpcode::JCC, 0, 0, 0, 20},
            {VmOpcode::JMP, 0, 0, 0, 19},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 20  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 20; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(20 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 4, 7, 0},
            {VmOpcode::JMP, 0, 0, 0, 19},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 19  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 19; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(19 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 16},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 16  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 16; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(16 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 13},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 13  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 13; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(13 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 10},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 10  (8 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 10; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(10 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 3, 0, 1},  // = 2
            {VmOpcode::MOVE, 80, 2, 4, 0},
            {VmOpcode::ADD, 80, 2, 3, 0},
            {VmOpcode::LOAD_CONST, 128, 3, 0, 10},  // = 4
            {VmOpcode::MOD, 80, 2, 3, 0},
            {VmOpcode::CMP, 80, 2, 10, 0},
            {VmOpcode::JCC, 1, 0, 0, 22},
            {VmOpcode::JMP, 0, 0, 0, 21},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 22  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 22; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(22 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 10, 4, 0},
            {VmOpcode::JMP, 0, 0, 0, 21},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 21  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 21; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(21 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 8},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 8  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 8; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(8 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 24},
            {VmOpcode::JMP, 0, 0, 0, 23},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 24  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 24; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(24 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 10, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 26},
            {VmOpcode::JMP, 0, 0, 0, 27},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 26  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 26; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(26 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 5, 9, 0},
            {VmOpcode::SUB, 80, 5, 7, 0},
            {VmOpcode::MOVE, 80, 9, 5, 0},
            {VmOpcode::JMP, 0, 0, 0, 25},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 27  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 27; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(27 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 10, 7, 0},
            {VmOpcode::JCC, 0, 0, 0, 29},
            {VmOpcode::JMP, 0, 0, 0, 30},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 29  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 29; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(29 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 5, 8, 0},
            {VmOpcode::ADD, 80, 5, 7, 0},
            {VmOpcode::MOVE, 80, 8, 5, 0},
            {VmOpcode::JMP, 0, 0, 0, 28},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 30  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 30; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(30 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 5, 0, 1},  // = 2
            {VmOpcode::CMP, 80, 10, 5, 0},
            {VmOpcode::JCC, 0, 0, 0, 32},
            {VmOpcode::JMP, 0, 0, 0, 33},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 32  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 32; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(32 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 5, 9, 0},
            {VmOpcode::ADD, 80, 5, 7, 0},
            {VmOpcode::MOVE, 80, 9, 5, 0},
            {VmOpcode::JMP, 0, 0, 0, 31},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 33  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 33; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(33 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 5, 0, 3},  // = 3
            {VmOpcode::CMP, 80, 10, 5, 0},
            {VmOpcode::JCC, 0, 0, 0, 35},
            {VmOpcode::JMP, 0, 0, 0, 34},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 35  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 35; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(35 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 5, 8, 0},
            {VmOpcode::SUB, 80, 5, 7, 0},
            {VmOpcode::MOVE, 80, 8, 5, 0},
            {VmOpcode::JMP, 0, 0, 0, 34},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 34  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 34; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(34 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 31},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 31  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 31; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(31 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 28},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 28  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 28; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(28 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 25},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 25  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 25; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(25 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 8, 7, 0},
            {VmOpcode::JCC, 2, 0, 0, 37},
            {VmOpcode::JMP, 0, 0, 0, 38},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 37  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 37; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(37 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 15, 7, 0},
            {VmOpcode::JMP, 0, 0, 0, 36},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 38  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 38; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(38 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 5, 0, 0},  // = 30
            {VmOpcode::CMP, 80, 8, 5, 0},
            {VmOpcode::JCC, 5, 0, 0, 37},
            {VmOpcode::JMP, 0, 0, 0, 39},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 39  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 39; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(39 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 9, 7, 0},
            {VmOpcode::JCC, 2, 0, 0, 37},
            {VmOpcode::JMP, 0, 0, 0, 40},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 40  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 40; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(40 * 37 + i);
        bb.instructions = {
            {VmOpcode::LOAD_CONST, 128, 5, 0, 2},  // = 15
            {VmOpcode::CMP, 80, 9, 5, 0},
            {VmOpcode::JCC, 5, 0, 0, 37},
            {VmOpcode::JMP, 0, 0, 0, 36},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 36  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 36; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(36 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 23},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 23  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 23; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(23 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 5, 6, 0},
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 42},
            {VmOpcode::JMP, 0, 0, 0, 41},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 42  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 42; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(42 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 8, 11, 0},
            {VmOpcode::JCC, 0, 0, 0, 45},
            {VmOpcode::JMP, 0, 0, 0, 43},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 44  (5 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 44; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(44 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 2, 13, 0},
            {VmOpcode::ADD, 80, 2, 7, 0},
            {VmOpcode::MOVE, 80, 13, 2, 0},
            {VmOpcode::MOVE, 80, 5, 7, 0},
            {VmOpcode::JMP, 0, 0, 0, 43},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 45  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 45; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(45 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 9, 12, 0},
            {VmOpcode::JCC, 0, 0, 0, 44},
            {VmOpcode::JMP, 0, 0, 0, 43},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 43  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 43; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(43 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 41},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 41  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 41; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(41 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 47},
            {VmOpcode::JMP, 0, 0, 0, 46},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 47  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 47; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(47 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 2, 14, 0},
            {VmOpcode::CMP, 80, 5, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 49},
            {VmOpcode::JMP, 0, 0, 0, 48},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 49  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 49; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(49 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 4, 14, 0},
            {VmOpcode::SUB, 80, 4, 7, 0},
            {VmOpcode::MOVE, 80, 2, 4, 0},
            {VmOpcode::JMP, 0, 0, 0, 48},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 48  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 48; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(48 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 4, 6, 0},
            {VmOpcode::JMP, 0, 0, 0, 50},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 50  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 50; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(50 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 4, 2, 0},
            {VmOpcode::JCC, 2, 0, 0, 51},
            {VmOpcode::JMP, 0, 0, 0, 52},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 51  (9 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 51; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(51 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 4, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 4},  // native_body_get_x
            {VmOpcode::MOVE, 80, 3, 0, 0},
            {VmOpcode::MOVE, 80, 0, 4, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 5},  // native_body_get_y
            {VmOpcode::MOVE, 80, 1, 0, 0},
            {VmOpcode::CMP, 80, 3, 8, 0},
            {VmOpcode::JCC, 0, 0, 0, 55},
            {VmOpcode::JMP, 0, 0, 0, 53},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 54  (2 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 54; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(54 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 15, 7, 0},
            {VmOpcode::JMP, 0, 0, 0, 53},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 55  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 55; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(55 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 1, 9, 0},
            {VmOpcode::JCC, 0, 0, 0, 54},
            {VmOpcode::JMP, 0, 0, 0, 53},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 53  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 53; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(53 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 1, 4, 0},
            {VmOpcode::ADD, 80, 1, 7, 0},
            {VmOpcode::MOVE, 80, 4, 1, 0},
            {VmOpcode::JMP, 0, 0, 0, 50},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 52  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 52; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(52 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 46},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 46  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 46; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(46 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 15, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 57},
            {VmOpcode::JMP, 0, 0, 0, 56},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 57  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 57; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(57 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 5, 7, 0},
            {VmOpcode::JCC, 0, 0, 0, 59},
            {VmOpcode::JMP, 0, 0, 0, 58},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 59  (4 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 59; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(59 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 2, 14, 0},
            {VmOpcode::ADD, 80, 2, 7, 0},
            {VmOpcode::MOVE, 80, 14, 2, 0},
            {VmOpcode::JMP, 0, 0, 0, 58},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 58  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 58; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(58 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 2, 14, 0},
            {VmOpcode::SUB, 80, 2, 7, 0},
            {VmOpcode::JMP, 0, 0, 0, 60},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 60  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 60; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(60 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 2, 6, 0},
            {VmOpcode::JCC, 5, 0, 0, 61},
            {VmOpcode::JMP, 0, 0, 0, 62},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 61  (6 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 61; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(61 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 2, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 6},  // native_body_shift
            {VmOpcode::MOVE, 80, 4, 2, 0},
            {VmOpcode::SUB, 80, 4, 7, 0},
            {VmOpcode::MOVE, 80, 2, 4, 0},
            {VmOpcode::JMP, 0, 0, 0, 60},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 62  (6 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 62; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(62 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 8, 0},
            {VmOpcode::MOVE, 80, 1, 9, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 7},  // native_body_set_head
            {VmOpcode::CMP, 80, 5, 6, 0},
            {VmOpcode::JCC, 0, 0, 0, 64},
            {VmOpcode::JMP, 0, 0, 0, 63},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 64  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 64; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(64 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 14, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 8},  // native_body_trim
            {VmOpcode::JMP, 0, 0, 0, 63},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 63  (3 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 63; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(63 * 37 + i);
        bb.instructions = {
            {VmOpcode::CMP, 80, 5, 7, 0},
            {VmOpcode::JCC, 0, 0, 0, 66},
            {VmOpcode::JMP, 0, 0, 0, 65},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 66  (12 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 66; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(66 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 14, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 9},  // native_place_apple
            {VmOpcode::MOVE, 80, 2, 0, 0},
            {VmOpcode::LOAD_CONST, 128, 4, 0, 11},  // = 65536
            {VmOpcode::MOVE, 80, 1, 2, 0},
            {VmOpcode::DIV, 80, 1, 4, 0},
            {VmOpcode::MOVE, 80, 11, 1, 0},
            {VmOpcode::LOAD_CONST, 128, 1, 0, 11},  // = 65536
            {VmOpcode::MOVE, 80, 4, 2, 0},
            {VmOpcode::MOD, 80, 4, 1, 0},
            {VmOpcode::MOVE, 80, 12, 4, 0},
            {VmOpcode::JMP, 0, 0, 0, 65},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 65  (9 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 65; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(65 * 37 + i);
        bb.instructions = {
            {VmOpcode::MOVE, 80, 0, 8, 0},
            {VmOpcode::MOVE, 80, 1, 9, 0},
            {VmOpcode::MOVE, 80, 2, 11, 0},
            {VmOpcode::MOVE, 80, 3, 12, 0},
            {VmOpcode::MOVE, 80, 4, 13, 0},
            {VmOpcode::MOVE, 80, 5, 14, 0},
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 10},  // native_draw
            {VmOpcode::NATIVE_CALL, 0, 0, 0, 11},  // native_sleep
            {VmOpcode::JMP, 0, 0, 0, 56},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 56  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 56; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(56 * 37 + i);
        bb.instructions = {
            {VmOpcode::JMP, 0, 0, 0, 2},
        };
        prog.bbs.push_back(std::move(bb));
    }

    // ── BB 4  (1 insns) ──
    {
        TestBB bb{};
        bb.bb_id = 4; bb.epoch = 0;
        bb.live_regs_bitmap = 0xFFFF; bb.flags = 0;
        for (int i = 0; i < 32; ++i)
            bb.epoch_seed[i] = static_cast<uint8_t>(4 * 37 + i);
        bb.instructions = {
            {VmOpcode::HALT, 0, 0, 0, 0},
        };
        prog.bbs.push_back(std::move(bb));
    }

    prog.native_sites = {
        {15, 3, 1},
        {19, 2, 7},
        {24, 2, 7},
        {31, 0, 0},
        {174, 1, 2},
        {177, 1, 3},
        {209, 1, 4},
        {216, 2, 5},
        {221, 1, 6},
        {227, 1, 10},
        {244, 6, 8},
        {245, 0, 9},
    };

    return prog;
}

} // namespace SnakeVM
