/// @file snake.cpp
/// @brief 2D terminal Snake — VM bytecode generated by py2vmp.py.
///
/// All game logic (direction, movement, collision, scoring) runs as
/// VMPilot VM instructions.  Only I/O and body-array management are
/// delegated to native C++ functions via NATIVE_CALL.
///
/// Regenerate the VM program:
///     python py2vmp.py snake_logic.py -o snake_vm.gen.hpp
///
/// Build & run:
///     cmake --build build --target snake_example
///     ./build/bin/snake_example

#include "snake_vm.gen.hpp"
#include "test_blob_builder.hpp"
#include "vm_engine.hpp"

#include <vm/vm_opcode.hpp>
#include <vm/vm_insn.hpp>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <vector>

// ─── Platform terminal I/O ──────────────────────────────────────────────

#if defined(_WIN32)
#include <conio.h>
#include <windows.h>

static void term_raw_on()  {}
static void term_raw_off() {}

static int term_read_key() {
    if (!_kbhit()) return 0;
    int c = _getch();
    if (c == 0 || c == 0xE0) {
        int ext = _getch();
        switch (ext) {
            case 72: return 'w';
            case 77: return 'd';
            case 80: return 's';
            case 75: return 'a';
        }
        return 0;
    }
    return c;
}

static void term_sleep_ms(int ms) { Sleep(static_cast<DWORD>(ms)); }

#else
#include <termios.h>
#include <unistd.h>
#include <sys/select.h>

static struct termios g_saved_termios;
static bool g_raw_active = false;

static void term_raw_on() {
    if (g_raw_active || !isatty(STDIN_FILENO)) return;
    tcgetattr(STDIN_FILENO, &g_saved_termios);
    struct termios raw = g_saved_termios;
    raw.c_lflag &= ~static_cast<tcflag_t>(ICANON | ECHO);
    raw.c_cc[VMIN]  = 0;
    raw.c_cc[VTIME] = 0;
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
    g_raw_active = true;
}

static void term_raw_off() {
    if (!g_raw_active) return;
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &g_saved_termios);
    g_raw_active = false;
}

static int term_read_key() {
    auto has_data = []() -> bool {
        fd_set fds;
        FD_ZERO(&fds);
        FD_SET(STDIN_FILENO, &fds);
        struct timeval tv = {0, 0};
        return select(STDIN_FILENO + 1, &fds, nullptr, nullptr, &tv) > 0;
    };
    auto getc_ = []() -> int {
        unsigned char c = 0;
        return (read(STDIN_FILENO, &c, 1) == 1) ? c : -1;
    };
    if (!has_data()) return 0;
    int c = getc_();
    if (c < 0) return 0;
    if (c == 0x1B) {
        if (!has_data()) return 0x1B;
        int c2 = getc_();
        if (c2 != '[') return 0;
        if (!has_data()) return 0;
        int c3 = getc_();
        switch (c3) {
            case 'A': return 'w';
            case 'B': return 's';
            case 'C': return 'd';
            case 'D': return 'a';
        }
        return 0;
    }
    return c;
}

static void term_sleep_ms(int ms) {
    usleep(static_cast<useconds_t>(ms) * 1000);
}
#endif

// ─── Game state (body array — managed by native functions) ──────────────

using namespace VMPilot::Runtime;
using namespace VMPilot::Common::VM;
using namespace VMPilot::Test;

static constexpr int GW = 30, GH = 15;

struct Segment { int x, y; };
static std::vector<Segment> g_body;

/// Latest values synced from VM registers via native_draw.
static int g_last_score = 0;
static size_t g_last_len = 0;

/// Shared key buffer — written by main's key-reading loop,
/// read by n_read_key inside the VM.
static volatile int g_last_key = 0;

// ─── Native functions (called via NATIVE_CALL from VM) ──────────────────
// Slot order must match NATIVE_MAP in snake_logic.py.

/// Slot 0: read keyboard (non-blocking)
static uint64_t n_read_key(uint64_t, uint64_t, uint64_t, uint64_t,
                            uint64_t, uint64_t, uint64_t, uint64_t) {
    int k = g_last_key;
    g_last_key = 0;
    return static_cast<uint64_t>(k);
}

/// Slot 1: initialise body array
static uint64_t n_body_init(uint64_t cx, uint64_t cy, uint64_t len,
                             uint64_t, uint64_t, uint64_t, uint64_t, uint64_t) {
    g_body.clear();
    for (uint64_t i = 0; i < len; ++i)
        g_body.push_back({static_cast<int>(cx - i), static_cast<int>(cy)});
    return 0;
}

/// Slot 2: get body[i].x
static uint64_t n_body_get_x(uint64_t i, uint64_t, uint64_t, uint64_t,
                              uint64_t, uint64_t, uint64_t, uint64_t) {
    return static_cast<uint64_t>(g_body[static_cast<size_t>(i)].x);
}

/// Slot 3: get body[i].y
static uint64_t n_body_get_y(uint64_t i, uint64_t, uint64_t, uint64_t,
                              uint64_t, uint64_t, uint64_t, uint64_t) {
    return static_cast<uint64_t>(g_body[static_cast<size_t>(i)].y);
}

/// Slot 4: shift body[j] = body[j-1]  (auto-extends vector if j == size)
static uint64_t n_body_shift(uint64_t j, uint64_t, uint64_t, uint64_t,
                              uint64_t, uint64_t, uint64_t, uint64_t) {
    auto idx = static_cast<size_t>(j);
    if (idx == 0) return 0;
    if (idx >= g_body.size())
        g_body.resize(idx + 1);
    g_body[idx] = g_body[idx - 1];
    return 0;
}

/// Slot 5: set head (body[0])
static uint64_t n_body_set_head(uint64_t x, uint64_t y, uint64_t, uint64_t,
                                 uint64_t, uint64_t, uint64_t, uint64_t) {
    if (!g_body.empty())
        g_body[0] = {static_cast<int>(x), static_cast<int>(y)};
    return 0;
}

/// Slot 6: trim — remove the segment at index [len] (shrink to len)
static uint64_t n_body_trim(uint64_t len, uint64_t, uint64_t, uint64_t,
                             uint64_t, uint64_t, uint64_t, uint64_t) {
    auto n = static_cast<size_t>(len);
    if (n < g_body.size())
        g_body.resize(n);
    return 0;
}

/// Slot 7: random number in [lo, hi]
static uint64_t n_random(uint64_t lo, uint64_t hi, uint64_t, uint64_t,
                          uint64_t, uint64_t, uint64_t, uint64_t) {
    if (hi <= lo) return lo;
    return lo + static_cast<uint64_t>(std::rand()) % (hi - lo + 1);
}

/// Slot 8: draw the game board
static uint64_t n_draw(uint64_t hx, uint64_t hy,
                        uint64_t ax, uint64_t ay,
                        uint64_t score, uint64_t body_len,
                        uint64_t, uint64_t) {
    int ihx = static_cast<int>(hx), ihy = static_cast<int>(hy);
    int iax = static_cast<int>(ax), iay = static_cast<int>(ay);
    g_last_score = static_cast<int>(score);
    g_last_len   = g_body.size();

    std::printf("\033[H");
    std::printf("  VMPilot Snake  |  Score: %d  |  Length: %zu  |  WASD/Arrows  Q=quit\n",
                static_cast<int>(score), g_body.size());

    for (int y = 0; y <= GH + 1; ++y) {
        for (int x = 0; x <= GW + 1; ++x) {
            if (y == 0 || y == GH + 1 || x == 0 || x == GW + 1) {
                std::putchar('#');
            } else if (x == ihx && y == ihy) {
                std::putchar('@');
            } else if (x == iax && y == iay) {
                std::putchar('*');
            } else {
                bool is_seg = false;
                for (size_t i = 1; i < g_body.size(); ++i) {
                    if (g_body[i].x == x && g_body[i].y == y) {
                        is_seg = true;
                        break;
                    }
                }
                std::putchar(is_seg ? 'o' : ' ');
            }
        }
        std::putchar('\n');
    }
    std::fflush(stdout);
    return 0;
}

/// Slot 9: sleep one frame
static uint64_t n_sleep(uint64_t, uint64_t, uint64_t, uint64_t,
                         uint64_t, uint64_t, uint64_t, uint64_t) {
    term_sleep_ms(100);
    return 0;
}

/// Slot 10: place apple avoiding body — returns (ax << 16) | ay
static uint64_t n_place_apple(uint64_t body_len_arg, uint64_t, uint64_t, uint64_t,
                               uint64_t, uint64_t, uint64_t, uint64_t) {
    auto blen = static_cast<size_t>(body_len_arg);
    int ax, ay;
    bool collision;
    do {
        ax = 1 + std::rand() % GW;
        ay = 1 + std::rand() % GH;
        collision = false;
        for (size_t i = 0; i < blen && i < g_body.size(); ++i) {
            if (g_body[i].x == ax && g_body[i].y == ay) {
                collision = true;
                break;
            }
        }
    } while (collision);
    return (static_cast<uint64_t>(ax) << 16) | static_cast<uint64_t>(ay);
}

// ─── Native function pointer table (indexed by NativeSlot) ──────────────

using NativeFn = uint64_t(*)(uint64_t,uint64_t,uint64_t,uint64_t,
                              uint64_t,uint64_t,uint64_t,uint64_t);

static const NativeFn g_native_table[] = {
    n_read_key,        // 0
    n_body_init,       // 1
    n_body_get_x,      // 2
    n_body_get_y,      // 3
    n_body_shift,      // 4
    n_body_set_head,   // 5
    n_body_trim,       // 6
    n_random,          // 7
    n_draw,            // 8
    n_sleep,           // 9
    n_place_apple,     // 10
};

static_assert(sizeof(g_native_table) / sizeof(g_native_table[0]) == SnakeVM::NATIVE_COUNT,
              "native table size must match NATIVE_COUNT");

// ─── Main ───────────────────────────────────────────────────────────────

int main() {
    std::srand(static_cast<unsigned>(std::time(nullptr)));

    // ── Build VM program from generated header ──────────────────────
    uint8_t seed[32];
    for (int i = 0; i < 32; ++i)
        seed[i] = static_cast<uint8_t>(i + 1);

    auto prog = SnakeVM::build();

    // Build native-call transition table
    std::vector<TestNativeCall> ncs;
    ncs.reserve(prog.native_sites.size());
    for (auto& ns : prog.native_sites) {
        TestNativeCall nc{};
        nc.call_site_ip = ns.global_ip;
        nc.arg_count    = ns.arg_count;
        nc.target_addr  = reinterpret_cast<uint64_t>(g_native_table[ns.slot]);
        ncs.push_back(nc);
    }

    auto blob = build_test_blob(seed, prog.bbs, SnakeVM::pool(), false, ncs);

    // Initial register values: r6=0 (ZERO), r7=1 (ONE)
    uint64_t regs[16] = {};
    regs[6] = 0;
    regs[7] = 1;

    auto engine = VmEngine<StandardPolicy, RollingKeyOram>::create(
        blob.data(), blob.size(), seed, 0, regs, 16);
    if (!engine) {
        std::fprintf(stderr, "VmEngine::create() failed\n");
        return 1;
    }

    // ── Pre-game screen ─────────────────────────────────────────────
    std::printf("\033[2J\033[H");
    std::printf("+-------------------------------+\n");
    std::printf("|       VMPilot Snake           |\n");
    std::printf("|-------------------------------|\n");
    std::printf("|  @ = you   o = body           |\n");
    std::printf("|  * = apple # = wall           |\n");
    std::printf("|                               |\n");
    std::printf("|  WASD or Arrow Keys to move   |\n");
    std::printf("|  Q to quit                    |\n");
    std::printf("+-------------------------------+\n");
    std::printf("\n  Starting in 2 seconds...\n");
    term_sleep_ms(2000);

    // ── Enter raw mode ──────────────────────────────────────────────
    term_raw_on();
    std::printf("\033[2J");

    // ── Step loop — poll keyboard between VM instructions ───────────
    bool running = true;
    uint64_t step_count = 0;
    while (running) {
        int key = term_read_key();
        if (key) g_last_key = key;

        auto step_result = engine->step();
        ++step_count;
        if (!step_result) {
            term_raw_off();
            std::fprintf(stderr,
                "\n  VM error after %llu steps (diagnostic: %d)\n",
                static_cast<unsigned long long>(step_count),
                static_cast<int>(step_result.error()));
            running = false;
        } else if (*step_result == VmResult::Halted) {
            running = false;
        }
    }

    // ── Restore terminal ────────────────────────────────────────────
    term_raw_off();
    std::printf("\n  GAME OVER!  Score: %d  |  Length: %zu  |  Steps: %llu\n\n",
                g_last_score, g_last_len,
                static_cast<unsigned long long>(step_count));
    return 0;
}
